---
title: "Homework 3"
date: "Due: 11:59pm, Wednesday, October 27"
output: 
  html_document: 
    css: hw.css
    theme: yeti
    toc: true
    fig_caption: false
    toc_float:
      collapsed: false
      smooth_scroll: true
---

## Instructions

Please make sure your final output file is a pdf document. You can submit handwritten solutions for non-programming exercises or type them using R Markdown, LaTeX or any other word processor. All programming exercises must be done in R, typed up clearly and with ALL code attached as an appendix. Submissions should be made on gradescope: go to Assignments $\rightarrow$ Homework 3.

You have learned to build hierarchical linear effects models (with particular emphasis on model selection and model assessment) within your teams. This homework is meant to demonstrate your ability to do something similar on your own.


## Estrogen Bioassay

This data is from: https://stat.duke.edu/datasets/estrogen-bioassay

### Introduction

Estrogens are a group of hormones produced in both the female ovaries and male testes, with larger amounts made in females than in males. They are particularly influential during puberty, menstruation, and pregnancy, but they also help regulate the growth of bones, skin, and other organs and tissues. In general, they have a strong effect of endocrine function by disrupting these functions.

Over the past 10 years, many synthetic compounds and plant products present in the environment have been found to affect hormonal functions in various ways. Those that have estrogenic activity have been labeled as environmental estrogens. There is increasing concern that chemicals in the environment referred to as environmental estrogens may be causing adverse effects through endocrine disruption. Hence, there is a need for new approaches for screening chemicals for endocrine disrupting effects. 

The rat uterotrophic bioassay provides one approach for identifying agonists or antagonists of estrogen. An estrogen antagonist is a compound that blocks the binding of estrogen and so blocks the action of estrogen. An estrogen agonist is a compound that enhances the action of estrogen. Rats in this study are either immature or have their ovaries removed and therefore do not produce estrogen. 

The point of the study is to use the rats as an assay to test the effect of estrogen agonists and antagonists on a particular hormonal response, the weight of the uterus. This is done by varying the amount of the agonist or antagonist give to the rat. The response is the weight of the uterus, with uterus weight expected to exhibit an increasing dose response trend for chemicals acting as estrogen agonists and with estrogen antagonists acting to block such estrogen effects. It is expected that the uterus gets heavier with the increase of estrogen agonist dose.

The basic design randomizes female rats to treatment groups, with groups consisting of a control group and several groups having increasing doses of the test agent. An international multi-laboratory study was conducted to compare the results of the rat uterotrophic bioassay using a known estrogen agonist (EE) and a known estrogen antagonist (ZM). The main goal of the study was to assess whether the results were consistent across the laboratories.


### Data

The data can be found in the file `bioassay.txt` on Sakai.


### Questions

Use a mixed effects model to answer the following questions of interest.

- Is the uterotrophic bioassay successful at identifying estrogenic effects of EE and anti-estrogenic effects of ZM. That is, after controlling for predictors and random effects, does uterus weight exhibit an increasing dose response trend for EE and a decreasing dose response trend for ZM?
- Does the dose response vary across labs? If so, are there certain labs that appear to be outliers?
- Do the protocols differ in their sensitivity to detecting EE and ZM effects? If so, is there one protocol that can be recommended?


### Code Book
      
Variable       |        Description
:------------- | :-------------------
protocol:      | A = immature female rats dosed by oral gavage (3 days) <br /> B = immature female rats dosed by injection (3 days) <br /> C = adult ovariectomized female rats dosed by injection (3 days) <br /> D = adult ovariectomized female rats dosed by injection (7 days)
uterus      |  Uterus weight (mg)
weight      |  Body weight of rat (g)
EE       | Dose of estrogen agonist, EE in mg/kg/day
ZM       | Dose of estrogen antagonist, ZM in mg/kg/day
lab       | Laboratory at which assay was conducted
group       | Lab replicate group (6 rats were used per group)



### Analyses

Prepare a written report (maximum of 5 pages) that includes the following:

- the final model you ultimately decided to use (all questions must be answered using a single model),
- clear model building, that is, justification for the models (e.g., why you chose certain transformations and why you decided the final model is reasonable),
- model assessment for the final model,
- the relevant regression output (includes: a table with coefficients and SEs, and confidence intervals),
- your interpretation of the results in the context of the questions of interest, including clear and direct answers to the questions posed, and
- any potential limitations of the analyses.

    
    



## Grading

Total: 20 points.
  
  
  