---
title: "Lab 3: Hospital Rankings (Part II)"
author: "Multilevel and hierarchical models"
output: 
  tufte::tufte_html:
    tufte_variant: "envisioned"
    highlight: pygments
    css: "lab.css"
    toc: true
link-citations: yes
---

```{r include=FALSE}
library(tidyverse)
library(tufte)
library(knitr)
options(
  htmltools.dir.version = FALSE, # for blogdown
  show.signif.stars = FALSE,     # for regression output
  digits = 2
  )
knitr::opts_chunk$set(eval = FALSE)
```


**Full TA Session**


# Housekeeping

<!-- ## R/RStudio -->
<!-- You all should have R and RStudio installed on your computers by now. If you do not, first install the latest version of R here: https://cran.rstudio.com (remember to select the right installer for your operating system). Next, install the latest version of RStudio here: https://www.rstudio.com/products/rstudio/download/. Scroll down to the "Installers for Supported Platforms" section and find the right installer for your operating system. -->


<!-- ## Gradescope -->
<!-- You MUST submit both your .Rmd and .pdf files to the course site on Gradescope here: https://www.gradescope.com/courses/281587/assignments. Do NOT create a zipped folder with the two documents but instead, upload them as two separate documents. Also, be sure to knit to pdf and NOT html; ask the TA about knitting to pdf if you cannot figure it out. Be sure to submit under the right assignment entry. Finally, when submitting your files, please select the corresponding pages for each exercise. -->



# Introduction
The goal of this lab is to reinforce concepts we have already covered in class. In class, we skipped through some of the minor details of the hierarchical models we have looked at, such as careful interpretation of results and basic model assessment. In this lab, the TA will walk you through some of those details using the same hospital data you started working on in the previous lab.



# The Data

We will again consider [data  from the Centers for Medicare and Medicaid Services on hospital costs and profit from the 2014 fiscal year](https://sta-610l-s21.github.io/Course-Website/labs/data/hc2014.RData). 

Our interest is in examining variability of net hospital income across states. In particular, we would like to rank the states by net income of hospitals. 

It is important to control for the potential influence of hospital ownership (in the variable called control) and of the number of beds (a proxy for hospital size). The ownership categories include Voluntary Nonprofit-Church, Voluntary Nonprofit-Other, Proprietary-Individual, Proprietary-Corporation, Proprietary-Partnership, Proprietary-Other, Governmental-Federal, Governmental-City-County, Governmental-County, Governmental-State, Governmental-Hospital District, Governmental-City, and Governmental-Other.


# Exercises

Describe a frequentist hierarchical normal model for capturing the association between ownership type and income, while controlling for the effect of the number of beds and the hierarchical structure of the data, through the states. 

The TA will walk you through how one would approach each of the following.

+ Exploratory data analysis investigating the relationship between the response and each predictor.
+ Investigating whether the inclusion of random intercepts and/or random slopes are necessary.
+ Clear specification of a final model and model fitting in R.
+ Basic model assessment (no need to check for leverage or influential points).
+ Uncertainty quantification around effect estimates of interest (no point estimates without uncertainty!).
+ Clear description of results in language accessible to a general scientifically-savvy reader.


No submissions are required at the end of this lab.



